import { NextRequest, NextResponse } from 'next/server'
import { createServerClient } from '@supabase/ssr'
import { createAdminClient } from '@/lib/supabase/admin'
import { resend, FROM_EMAIL } from '@/lib/resend/client'
import { rateLimit } from '@/lib/rateLimit'

export const runtime = 'edge';

function createAuthClient(request: NextRequest) {
  return createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() { return request.cookies.getAll() },
        setAll() {},
      },
    }
  )
}

const EMAIL_HEADER = `
  <div style="text-align: center; margin-bottom: 40px;">
    <h1 style="color: #C9A84C; font-family: 'Cinzel', Georgia, serif; font-size: 28px; letter-spacing: 6px; margin: 0;">CZAAH</h1>
    <p style="color: rgba(255,255,255,0.4); font-size: 11px; letter-spacing: 4px; margin-top: 8px;">CAPITAL · VENTURES · INFRASTRUCTURE</p>
  </div>
`

const EMAIL_FOOTER = `
  <p style="color: rgba(255,255,255,0.3); font-size: 12px; text-align: center; margin-top: 32px;">
    &copy; 2026 CZAAH. All rights reserved.
  </p>
`

function wrapEmail(inner: string) {
  return `
    <div style="font-family: 'Raleway', Arial, sans-serif; background: #000000; color: #ffffff; padding: 40px 20px; max-width: 600px; margin: 0 auto;">
      ${EMAIL_HEADER}
      <div style="background: #080808; border: 1px solid #1A1A1A; border-radius: 8px; padding: 32px;">
        ${inner}
      </div>
      ${EMAIL_FOOTER}
    </div>
  `
}

export async function POST(request: NextRequest) {
  try {
    // Authenticate user
    const userClient = createAuthClient(request)
    const { data: { user }, error: authError } = await userClient.auth.getUser()
    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Rate limit: 10 per hour per user
    const { success: rateLimitOk } = rateLimit(`enquiries:${user.id}`, 10, 3600000)
    if (!rateLimitOk) {
      return NextResponse.json({ error: 'Too many requests. Please try again later.' }, { status: 429 })
    }

    const body = await request.json()
    const {
      sectorId,
      serviceId,
      productId,
      productName,
      description,
      estimatedQuantity,
      timeline,
      additionalNotes,
      attachments,
    } = body

    // Check attachment file sizes (10MB max each)
    const maxSize = 10 * 1024 * 1024 // 10MB
    if (attachments && Array.isArray(attachments)) {
      for (const attachment of attachments) {
        if (attachment.fileData && Buffer.from(attachment.fileData, 'base64').length > maxSize) {
          return NextResponse.json({ error: 'File too large. Maximum size is 10MB.' }, { status: 413 })
        }
      }
    }

    if (!sectorId || !productName || !description || !estimatedQuantity || !timeline) {
      return NextResponse.json(
        { error: 'Missing required fields: sectorId, productName, description, estimatedQuantity, timeline' },
        { status: 400 }
      )
    }

    const supabase = createAdminClient()

    // Insert enquiry (reference_number is auto-generated by DB default)
    const { data: enquiry, error: insertError } = await supabase
      .from('enquiries')
      .insert({
        member_id: user.id,
        sector_id: sectorId,
        service_id: serviceId || null,
        product_id: productId || null,
        product_name: productName,
        description,
        estimated_quantity: estimatedQuantity,
        timeline,
        additional_notes: additionalNotes || null,
        status: 'submitted',
      })
      .select()
      .single()

    if (insertError || !enquiry) {
      return NextResponse.json({ error: insertError?.message || 'Failed to create enquiry' }, { status: 500 })
    }

    // Upload attachments if provided
    if (attachments && Array.isArray(attachments) && attachments.length > 0) {
      for (const attachment of attachments) {
        const { fileName, fileData } = attachment
        if (!fileName || !fileData) continue

        const buffer = Buffer.from(fileData, 'base64')
        const filePath = `enquiries/${enquiry.id}/${fileName}`

        const { error: uploadError } = await supabase.storage
          .from('platform-files')
          .upload(filePath, buffer, {
            contentType: 'application/octet-stream',
            upsert: false,
          })

        if (uploadError) {
          console.error(`Failed to upload attachment ${fileName}:`, uploadError.message)
          continue
        }

        await supabase.from('enquiry_attachments').insert({
          enquiry_id: enquiry.id,
          file_url: filePath,
          file_name: fileName,
          uploaded_by: user.id,
        })
      }
    }

    const { data: memberProfile } = await supabase
      .from('profiles')
      .select('full_name, email, role')
      .eq('id', user.id)
      .single()

    // Elite Members get priority handling: their enquiries are flagged so
    // staff can spot and pick them up first, ahead of the general queue.
    const isPriority = memberProfile?.role === 'elite_member'

    // Notify all super_admins
    const { data: superAdmins } = await supabase
      .from('profiles')
      .select('id')
      .eq('role', 'super_admin')

    if (superAdmins && superAdmins.length > 0) {
      const notifications = superAdmins.map((admin) => ({
        user_id: admin.id,
        type: 'enquiry_assigned' as const,
        title: isPriority ? '⭐ Priority Enquiry — Elite Member' : 'New Enquiry Submitted',
        body: `New enquiry ${enquiry.reference_number} has been submitted and requires assignment.`,
        link: `/admin/enquiries/${enquiry.id}`,
        is_read: false,
      }))

      await supabase.from('notifications').insert(notifications)
    }

    // Send email to info@czaah.com

    await resend.emails.send({
      from: FROM_EMAIL,
      to: 'info@czaah.com',
      subject: `${isPriority ? '⭐ Priority — ' : ''}New Enquiry — ${enquiry.reference_number}`,
      html: wrapEmail(`
        <h2 style="color: #C9A84C; font-size: 20px; margin: 0 0 16px 0;">New Enquiry Submitted</h2>
        <p style="color: rgba(255,255,255,0.6); line-height: 1.6; margin: 0 0 16px 0;">
          A new enquiry has been submitted and requires attention.
        </p>
        <table style="width: 100%; border-collapse: collapse; margin: 0 0 24px 0;">
          <tr>
            <td style="color: rgba(255,255,255,0.4); padding: 8px 0; font-size: 13px;">Reference</td>
            <td style="color: #ffffff; padding: 8px 0; font-size: 13px;">${enquiry.reference_number}</td>
          </tr>
          <tr>
            <td style="color: rgba(255,255,255,0.4); padding: 8px 0; font-size: 13px;">Member</td>
            <td style="color: #ffffff; padding: 8px 0; font-size: 13px;">${memberProfile?.full_name || 'N/A'}</td>
          </tr>
          <tr>
            <td style="color: rgba(255,255,255,0.4); padding: 8px 0; font-size: 13px;">Product</td>
            <td style="color: #ffffff; padding: 8px 0; font-size: 13px;">${productName}</td>
          </tr>
          <tr>
            <td style="color: rgba(255,255,255,0.4); padding: 8px 0; font-size: 13px;">Timeline</td>
            <td style="color: #ffffff; padding: 8px 0; font-size: 13px;">${timeline}</td>
          </tr>
        </table>
        <a href="https://czaah.com/admin/enquiries/${enquiry.id}" style="display: inline-block; background: #C9A84C; color: #000000; padding: 12px 32px; border-radius: 4px; text-decoration: none; font-weight: 600; font-size: 14px;">
          View Enquiry &rarr;
        </a>
      `),
    })

    return NextResponse.json({ data: enquiry }, { status: 201 })
  } catch (err) {
    console.error('POST /api/enquiries error:', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}

export async function GET(request: NextRequest) {
  try {
    const userClient = createAuthClient(request)
    const { data: { user }, error: authError } = await userClient.auth.getUser()
    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const supabase = createAdminClient()

    // Get user profile for role
    const { data: profile } = await supabase
      .from('profiles')
      .select('role')
      .eq('id', user.id)
      .single()

    if (!profile) {
      return NextResponse.json({ error: 'Profile not found' }, { status: 404 })
    }

    const { searchParams } = new URL(request.url)
    const status = searchParams.get('status')
    const sectorId = searchParams.get('sector_id')

    let query = supabase
      .from('enquiries')
      .select('*, profiles!enquiries_member_id_fkey(full_name, email, company_name, role)')
      .order('created_at', { ascending: false })

    // Filter by role
    if (profile.role === 'member' || profile.role === 'elite_member' || profile.role === 'real_estate_partner') {
      query = query.eq('member_id', user.id)
    } else if (profile.role === 'admin') {
      // Admins see enquiries assigned to them OR created by them
      query = query.or(`assigned_admin_id.eq.${user.id},member_id.eq.${user.id}`)
    }
    // super_admin sees all

    // Apply optional filters
    if (status) {
      query = query.eq('status', status)
    }
    if (sectorId) {
      query = query.eq('sector_id', sectorId)
    }

    const { data: enquiries, error: queryError } = await query

    if (queryError) {
      return NextResponse.json({ error: queryError.message }, { status: 500 })
    }

    return NextResponse.json({ data: enquiries })
  } catch (err) {
    console.error('GET /api/enquiries error:', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
